name: "CI"
on: [push, pull_request]
jobs:
  soundness:
    name: Soundness Check
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Bootstrap Mint
        uses: irgaly/setup-mint@v1

      - name: Run soundness
        run: |
          scripts/soundness.sh
          exit $(git status --porcelain | wc -l)

  unit-test:
    name: Unit Test
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        swift: ["6.0", "latest"]

    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.2.0
        with:
          toolchain: ${{ matrix.swift }}
        env:
          SWIFTLY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Resolve Swift dependencies
        run: swift package resolve

      - name: Run Unit Tests
        run: swift test --enable-code-coverage

      - name: Merge code coverage
        if: matrix.swift == 'latest'
        run: |
          llvm-cov export -format "lcov" \
            .build/debug/swift-otelPackageTests.xctest \
            -ignore-filename-regex="\/Tests\/" \
            -ignore-filename-regex="\/Generated\/" \
            -ignore-filename-regex="\/.build\/" \
            -instr-profile=./.build/debug/codecov/default.profdata \
          > info.lcov

      - name: Upload code coverage report to Codecov
        if: matrix.swift == 'latest'
        uses: codecov/codecov-action@v5.4.3
        with:
          files: ./info.lcov
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  compile-counter-example:
    name: Compile Counter Example
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./Examples/Counter
    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.2.0
        with:
          toolchain: latest
        env:
          SWIFTLY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Resolve Swift dependencies
        run: swift package resolve
      - name: Build
        run: swift build
